name: RileyLester
favicon: null
layout_spectrum: 0
typography_spectrum: 0.09264666051603854
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0
  lightness: 0.6699674553237855
  saturation: 0.37537275813519955
  rhythmicContrast: 0.03709579398855567
purpose: []
